<link rel="stylesheet" type="text/css" 
href="<?= /* @noEscape */ $block->getViewFileUrl('Unicodesystems_Bannerslider::css/flexslider.css')?>">
<link rel="stylesheet" type="text/css" 
href="<?= /* @noEscape */ $block->getViewFileUrl('Unicodesystems_Bannerslider::css/evolution.css')?>">
<?php $sliderpreviewId = $block->getRequest()->getParam('sliderpreview_id') ?>
<script type="text/javascript">
require(['jquery', 'unicodesystems/flexslider'], function($) {
    $(document).ready(function($) {
        var STYLESLIDE_FLEXSLIDER_ONE =
        <?= \Unicodesystems\Bannerslider\Model\Slider::STYLESLIDE_FLEXSLIDER_ONE ?>;
        var STYLESLIDE_FLEXSLIDER_TWO =
        <?= \Unicodesystems\Bannerslider\Model\Slider::STYLESLIDE_FLEXSLIDER_TWO ?>;
        var STYLESLIDE_FLEXSLIDER_THREE =
        <?= \Unicodesystems\Bannerslider\Model\Slider::STYLESLIDE_FLEXSLIDER_THREE ?>;

        switch (<?= /* @noEscape */ $sliderpreviewId ?>) {
            case STYLESLIDE_FLEXSLIDER_ONE:
                $('.flexslider').flexslider({
                    animation: "slide"
                });
                break;
            case STYLESLIDE_FLEXSLIDER_TWO:
                $('.flexslider').flexslider({
                    animation: "slide",
                    controlNav: "thumbnails"
                });
                break;
            case STYLESLIDE_FLEXSLIDER_THREE:
                $('#carousel').flexslider({
                    animation: "slide",
                    controlNav: false,
                    animationLoop: false,
                    slideshow: false,
                    itemWidth: 210,
                    itemMargin: 5,
                    asNavFor: '#flexslider'
                });

                $('#flexslider').flexslider({
                    animation: "slide",
                    controlNav: false,
                    animationLoop: false,
                    slideshow: false,
                    sync: "#carousel"
                });
                break;
            default:
                $('.flexslider').flexslider({
                    animation: "slide",
                    animationLoop: false,
                    itemWidth: 400,
                    itemMargin: 5,
                    minItems: 2,
                    maxItems: 4
                });
                break;
        }

    });
});
</script>
<div style="width: 500; margin: auto">
    <?php if ($sliderpreviewId == \Unicodesystems\Bannerslider\Model\Slider::STYLESLIDE_FLEXSLIDER_TWO) : ?>
    <div id="flexslider" class="flexslider" style="margin:auto">
        <ul class="slides">
            <li data-thumb="<?= /* @noEscape */
            $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/4.jpg')?>">
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/4.jpg')?>"
                height="500px" />
            </li>

            <li data-thumb="<?= /* @noEscape */
            $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/1.jpg')?>">
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/1.jpg') ?>"  height="500px" />
            </li>

            <li data-thumb="<?= /* @noEscape */
            $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/2.jpg')?>">
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/2.jpg') ?>"  height="500px" />
            </li>
            <li data-thumb="<?= /* @noEscape */
            $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/3.jpg')?>">
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/3.jpg') ?>"  height="500px" />
            </li>
        </ul>
    </div>
    <?php else :
        ?>
    <div id="flexslider" class="flexslider" style="margin:auto">
        <ul class="slides">
            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/4.jpg')?>"  height="500px" />
            </li>

            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/1.jpg') ?>"  height="500px" />
            </li>

            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/2.jpg') ?>"  height="500px" />
            </li>
            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/3.jpg') ?>"  height="500px" />
            </li>
        </ul>
    </div>
    <?php endif; ?>

    <?php if ($sliderpreviewId == \Unicodesystems\Bannerslider\Model\Slider::STYLESLIDE_FLEXSLIDER_THREE) :
        ?>
    <div id="carousel" class="flexslider" style="margin:auto">
        <ul class="slides">
            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/4.jpg')?>"/>
            </li>

            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/1.jpg') ?>"/>
            </li>

            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/2.jpg') ?>" />
            </li>
            <li>
                <img src="<?= /* @noEscape */
                $block->getViewFileUrl('Unicodesystems_Bannerslider::images/demo/3.jpg') ?>" />
            </li>
        </ul>
    </div>
    <?php endif; ?>
</div>
